server {
#    listen ${PORT} default_server;
    listen 80 default_server;
#    listen [::]:${PORT} default_server;
    listen [::]:80 default_server;
    server_name _;

    # Adjust based on your max expected file upload size
    client_max_body_size 50M;

    location / {
        resolver [fd12::10] ipv6=on valid=2s;

        # CRUCIAL: Match the service name of your Gunicorn app in Railway
        # Syntax: http://<gunicorn-service-name>.railway.internal:<port>
        set $backend "djangoscraper.railway.internal:8000";
        proxy_pass http://$backend;
        
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #proxy_set_header X-Forwarded-Proto $scheme;  # Problematic for Railway because it already terminates TLS, so nginx only sees scheme == http
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        
        # Recommended for real-time features like WebSockets or SSE streaming
        proxy_buffering off;
        proxy_redirect off;
    }
}
