"""
Django settings for django_scraper project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ, os


# cf. django-environ:  https://django-environ.readthedocs.io/en/latest/

env = environ.Env(
    DEBUG=(bool, True)  # If given .env file does not specify, assume DEBUG is True
)

SITE_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
environ.Env.read_env(os.path.join(SITE_ROOT, ".env"))

DEBUG = env("DEBUG")
SECRET_KEY = env.str("SECRET_KEY")
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'huey.contrib.djhuey',
    'tracking',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_scraper.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_scraper.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Env-driven via django-environ's DB-URL support. The default keeps the local
# SQLite file (dev/test), so the suite runs with no DATABASE_URL, no Postgres,
# and no network. Point at Postgres in production by setting DATABASE_URL, e.g.
# ``DATABASE_URL=postgres://user:pass@host:5432/dbname`` (needs psycopg,
# already in requirements.txt). See docs/postgres_migration.md.

DATABASES = {
    "default": env.db_url(
        "DATABASE_URL",
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "America/Halifax"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Scraping / rate limiting
SCRAPE_REQUEST_DELAY_SECONDS = env.float("SCRAPE_REQUEST_DELAY_SECONDS", default=3.0)
SCRAPE_REQUEST_DELAY_JITTER_SECONDS = env.float(
    "SCRAPE_REQUEST_DELAY_JITTER_SECONDS", default=1.0
)
SCRAPE_REQUEST_TIMEOUT_SECONDS = env.int("SCRAPE_REQUEST_TIMEOUT_SECONDS", default=30)
# Maximum size (in bytes) of a single search response before it is rejected as
# oversized. Guards against huge JSON payloads (e.g. large Storepass responses).
# Set to 0 (or leave unset with default) to disable the cap; 0/None = unlimited.
SCRAPE_MAX_RESPONSE_BYTES = env.int("SCRAPE_MAX_RESPONSE_BYTES", default=8_000_000)

# Background tasks (Huey + Redis)
# Redis connection string for the Huey consumer/producer. Only required when
# actually running the background worker (`python manage.py run_huey`).
REDIS_URL = env.str("REDIS_URL", default="redis://localhost:6379/0")
# ``immediate`` runs tasks synchronously in-process with NO Redis needed, which
# is what dev and the test suite rely on. It defaults to DEBUG (True in dev/test)
# so the suite passes without a Redis server; set HUEY_IMMEDIATE=False (with
# DEBUG on) or run with DEBUG off to exercise the real Redis-backed queue.
HUEY = {
    "huey_class": "huey.RedisHuey",
    "name": "django_scraper",
    "immediate": env.bool("HUEY_IMMEDIATE", default=DEBUG),
    "connection": {"url": REDIS_URL},
    "consumer": {
        "workers": 2,
        "worker_type": "thread",
    },
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "tracking": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
