# Generated by Django 5.2.5 on 2025-08-14 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=125, verbose_name='Text to be used for identifying and when searching for item')),
                ('priority', models.IntegerField(choices=[(0, 'S'), (1, 'A'), (2, 'B'), (3, 'C')], default=2, verbose_name="Priority for this item's acquisition")),
                ('active', models.BooleanField(default=True, verbose_name='Indicate whether item should be actively updated or not')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('name', models.CharField(verbose_name='User-given name for this search source')),
                ('key', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='String key indicating which Parser should be used when searching with this Source')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.searchableitem', verbose_name='Item for this search source')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.source', verbose_name='Eligible search source for this item')),
            ],
        ),
        migrations.CreateModel(
            name='WebUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='tracking_we_timesta_e1602e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title returned in search result')),
                ('price', models.FloatField(verbose_name='Price returned in search result')),
                ('category', models.CharField(blank=True, max_length=250, null=True, verbose_name='Category returned in search result')),
                ('instock', models.SmallIntegerField(blank=True, default=1, verbose_name='In-stock status returned in search result')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='results', to='tracking.searchableitem', verbose_name='Item associated with this search result')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='results', to='tracking.source', verbose_name='Search source associated with this search result')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='results', to='tracking.webupdate', verbose_name='Set of search results from a single web update')),
            ],
        ),
    ]
