# Generated by Django 6.0.6 on 2026-07-07 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_searchresult_search_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=125)),
                ('search_url', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('success', 'Success'), ('http_error', 'HTTP error'), ('parse_error', 'Parse error'), ('config_error', 'Configuration error'), ('empty', 'No results')], max_length=20)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('result_count', models.PositiveSmallIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.searchableitem')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.source')),
                ('webupdate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_jobs', to='tracking.webupdate')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['webupdate', 'status'], name='tracking_fe_webupda_577ee4_idx')],
            },
        ),
    ]
