# Generated by Django 6.0.6 on 2026-07-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_fetchjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsource',
            name='title_exclude_patterns',
            field=models.JSONField(blank=True, default=list, verbose_name='Regex patterns; matching titles are excluded'),
        ),
        migrations.AddField(
            model_name='itemsource',
            name='title_include_patterns',
            field=models.JSONField(blank=True, default=list, verbose_name='Regex patterns; result title must match at least one if non-empty'),
        ),
    ]
