# Generated by Django 6.0.6 on 2026-07-08 14:24

from django.db import migrations, models


def backfill_parser_key(apps, schema_editor):
    Source = apps.get_model("tracking", "Source")
    for src in Source.objects.filter(parser_key=""):
        src.parser_key = src.key
        src.save(update_fields=["parser_key"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_itemsource_title_patterns'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='page_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Optional results-per-page hint for paginated APIs (used in Phase 3)'),
        ),
        migrations.AddField(
            model_name='source',
            name='parser_key',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name="Parser registry key (e.g. 'shopify', 'storepass'); blank falls back to 'key'"),
        ),
        migrations.AddField(
            model_name='source',
            name='request_headers',
            field=models.JSONField(blank=True, default=dict, verbose_name='Extra HTTP headers sent with search requests (e.g. Accept/Origin/Referer)'),
        ),
        migrations.AlterField(
            model_name='source',
            name='base_search_url',
            field=models.CharField(max_length=1000, verbose_name='Search URL template; use {term} for the URL-encoded query string'),
        ),
        migrations.AlterField(
            model_name='source',
            name='key',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='String key indicating which Parser should be used when searching with this Source'),
        ),
        migrations.RunPython(backfill_parser_key, noop),
    ]
