# Generated by Django 6.0.6 on 2026-07-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_itemsource_unique_item_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='key',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name="Short abbreviation identifying this source (user-facing; e.g. 'cc')"),
        ),
        migrations.AlterField(
            model_name='source',
            name='page_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Optional results-per-page hint for paginated APIs'),
        ),
        migrations.AlterField(
            model_name='source',
            name='parser_key',
            field=models.CharField(max_length=20, verbose_name="Parser registry key selecting which parser handles this source (e.g. 'shopify', 'storepass')"),
        ),
    ]
