# Generated by Django 6.0.6 on 2026-07-08 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_alter_source_key_alter_source_page_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='max_pages',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Max pages to fetch per search (1 = single page)'),
        ),
        migrations.AddField(
            model_name='webupdate',
            name='completed_searches',
            field=models.PositiveIntegerField(default=0, verbose_name='Item-source searches completed so far'),
        ),
        migrations.AddField(
            model_name='webupdate',
            name='error_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Failed searches in this run'),
        ),
        migrations.AddField(
            model_name='webupdate',
            name='result_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Price results stored by this run'),
        ),
        migrations.AddField(
            model_name='webupdate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Background run status'),
        ),
        migrations.AddField(
            model_name='webupdate',
            name='total_searches',
            field=models.PositiveIntegerField(default=0, verbose_name='Total item-source searches planned for this run'),
        ),
        migrations.AlterField(
            model_name='fetchjob',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('http_error', 'HTTP error'), ('parse_error', 'Parse error'), ('config_error', 'Configuration error'), ('empty', 'No results'), ('oversized', 'Response too large')], max_length=20),
        ),
        migrations.CreateModel(
            name='UpdateSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Human-readable name for this schedule')),
                ('frequency', models.CharField(choices=[('hourly', 'Hourly'), ('twice_daily', 'Twice Daily'), ('daily', 'Daily')], default='daily', max_length=20, verbose_name='How often this scrape runs')),
                ('anchor_time', models.TimeField(verbose_name='Reference time-of-day (America/Halifax) used to place runs')),
                ('enabled', models.BooleanField(default=True, verbose_name='Whether this schedule is active')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='When this schedule last dispatched a run (UTC)')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='tracking.tag', verbose_name='Limit runs to active items with this tag (blank = all active items)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
