# Generated by Django 6.0.6 on 2026-07-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_source_max_pages_webupdate_completed_searches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsource',
            name='pinned_url',
            field=models.URLField(blank=True, default='', max_length=1000, verbose_name='Pinned result URL — fetch this directly instead of running a search'),
        ),
        migrations.AddField(
            model_name='source',
            name='http_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=4, verbose_name='HTTP method for search requests'),
        ),
        migrations.AddField(
            model_name='source',
            name='request_body_template',
            field=models.JSONField(blank=True, default=dict, verbose_name='POST request body template; use {term} in string leaves for the search term'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price returned in search result'),
        ),
    ]
