# Generated by Django 6.0.6 on 2026-07-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_itemsource_pinned_url_source_http_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchjob',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('http_error', 'HTTP error'), ('parse_error', 'Parse error'), ('config_error', 'Configuration error'), ('empty', 'No results'), ('oversized', 'Response too large'), ('blocked', 'Blocked')], max_length=20),
        ),
        migrations.AlterField(
            model_name='source',
            name='max_pages',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Max pages to fetch per search (1 = single page). GET sources paginate via parser ``next_page_url``; POST sources require parser ``next_page_body`` support.'),
        ),
    ]
