# Generated by Django 6.0.6 on 2026-07-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_alter_fetchjob_status_alter_source_max_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchjob',
            name='stored_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='SearchResult rows stored for this job after dedup'),
        ),
        migrations.AddField(
            model_name='webupdate',
            name='skipped_duplicate_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Parsed results skipped as unchanged duplicates this run'),
        ),
    ]
