# Generated by Django 6.0.6 on 2026-08-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0015_fetchjob_stored_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='rate_limit_profile',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name="Rate-limit profile registry key selecting how this source's budget is extracted and paced (e.g. 'ietf', 'x-ratelimit', 'graphql_cost'); blank/'none' keeps the fixed-delay pacing all sources use today"),
        ),
    ]
