# Generated by Django 6.0.6 on 2026-08-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0016_source_rate_limit_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchjob',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('http_error', 'HTTP error'), ('parse_error', 'Parse error'), ('config_error', 'Configuration error'), ('empty', 'No results'), ('oversized', 'Response too large'), ('blocked', 'Blocked'), ('give_up', 'Gave up')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='fetchjob',
            constraint=models.UniqueConstraint(fields=('webupdate', 'item', 'source'), name='unique_fetchjob_per_webupdate_item_source'),
        ),
    ]
