# Generated by Django 6.0.6 on 2026-08-19 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0017_alter_fetchjob_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchableitem',
            name='expected_category',
            field=models.CharField(blank=True, default='', max_length=125, verbose_name='Expected category/set (e.g. a specific MTG set) a result must contain to narrow results beyond product-line disambiguation. Independent of expected product line; blank disables this check.'),
        ),
        migrations.AddField(
            model_name='searchableitem',
            name='expected_product_line',
            field=models.CharField(blank=True, default='', max_length=125, verbose_name="Expected product line (e.g. 'Magic', 'Pokemon') a result must contain to disambiguate this item from a same-titled item in an unrelated product line. Blank disables this check."),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='product_line',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Product line returned in search result'),
        ),
        migrations.CreateModel(
            name='ObservedCategoryValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('category', 'Category'), ('product_line', 'Product line')], max_length=20, verbose_name='Which signal this value was observed for')),
                ('value', models.CharField(max_length=250, verbose_name='Raw value as observed from the vendor response')),
                ('last_seen', models.DateTimeField(verbose_name='When this value was most recently observed')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.source', verbose_name='Source this value was observed from')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'field_name'], name='tracking_ob_source__0be76d_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'field_name', 'value'), name='unique_observed_category_value')],
            },
        ),
    ]
