# Generated by Django 6.0.6 on 2026-08-19 16:47

from django.db import migrations
from django.db.models import Max


def backfill_observed_category_values(apps, schema_editor):
    """Seed ObservedCategoryValue(field_name="category") from historical SearchResult data.

    Restores immediate suggestion coverage for the ``category`` axis on deploy
    (see design.md Decision 9). ``product_line`` has no equivalent historical
    source — it was never captured before this change — and starts cold.
    """
    SearchResult = apps.get_model("tracking", "SearchResult")
    ObservedCategoryValue = apps.get_model("tracking", "ObservedCategoryValue")

    observed = (
        SearchResult.objects.exclude(category__isnull=True)
        .exclude(category="")
        .values("source_id", "category")
        .annotate(last_seen=Max("update__timestamp"))
    )
    for row in observed:
        ObservedCategoryValue.objects.update_or_create(
            source_id=row["source_id"],
            field_name="category",
            value=row["category"],
            defaults={"last_seen": row["last_seen"]},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0018_searchableitem_expected_category_and_more'),
    ]

    operations = [
        migrations.RunPython(
            backfill_observed_category_values, migrations.RunPython.noop
        ),
    ]
