# Generated by Django 6.0.6 on 2026-08-19 17:41

import json

from django.db import migrations, models


def convert_expected_fields_to_lists(apps, schema_editor):
    """Wrap each item's existing plain-text expected_product_line/expected_category
    string into a single-item list (or an empty list for a blank string).

    Runs before the AlterField operations below, while the fields are still
    CharField in this migration's historical model state — writing a
    json.dumps()'d string through .update() here just stores plain text in the
    existing text column, which the following AlterField(JSONField) then reads
    back correctly via json.loads().
    """
    SearchableItem = apps.get_model("tracking", "SearchableItem")
    for item in SearchableItem.objects.all():
        SearchableItem.objects.filter(pk=item.pk).update(
            expected_product_line=json.dumps(
                [item.expected_product_line] if item.expected_product_line else []
            ),
            expected_category=json.dumps(
                [item.expected_category] if item.expected_category else []
            ),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0019_backfill_observed_category_values'),
    ]

    operations = [
        migrations.RunPython(
            convert_expected_fields_to_lists, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='searchableitem',
            name='expected_category',
            field=models.JSONField(blank=True, default=list, verbose_name='Expected category/set value(s) (e.g. a specific MTG set, possibly spelled differently per vendor) — a result must contain at least one listed value to narrow results beyond product-line disambiguation. Independent of expected product line; empty list disables this check.'),
        ),
        migrations.AlterField(
            model_name='searchableitem',
            name='expected_product_line',
            field=models.JSONField(blank=True, default=list, verbose_name="Expected product line(s) (e.g. ['Magic'], or ['Magic', 'MTG'] when vendors word it differently) — a result must contain at least one listed value to disambiguate this item from a same-titled item in an unrelated product line. Empty list disables this check."),
        ),
    ]
