# Generated by Django 6.0.6 on 2026-08-20 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0020_alter_searchableitem_expected_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchableitem',
            name='metadata_provider_key',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name="Metadata provider registry key selecting which external metadata provider enriches this item (e.g. 'scryfall'); blank disables metadata enrichment"),
        ),
        migrations.CreateModel(
            name='ItemMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unfetched', 'Unfetched'), ('pending', 'Pending'), ('matched', 'Matched'), ('needs_review', 'Needs review'), ('no_match', 'No match'), ('error', 'Error')], default='unfetched', max_length=20, verbose_name='Current metadata resolution/fetch status')),
                ('external_id', models.CharField(blank=True, default='', max_length=250, verbose_name="Provider's resolved external identifier for the current match, if any")),
                ('pinned_external_id', models.CharField(blank=True, default='', max_length=250, verbose_name='Operator-set manual override identifier — sticky and authoritative once set; exempts the item from the text-change re-fetch trigger')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Opaque raw data as returned by the provider')),
                ('fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='When this record was last updated by a fetch')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='tracking.searchableitem', verbose_name='Item this fetched metadata belongs to')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataFetchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.searchableitem', verbose_name='Item to (re-)fetch metadata for')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'requested_at'], name='tracking_me_status_b0fe19_idx')],
            },
        ),
    ]
