# Generated by Django 6.0.6 on 2026-10-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0022_expected_value_vendor_provenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_reset_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('last_update_started_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
